################################################################
## Tree clade comparison between methods
##
## Author: Jana S. Huisman
## Last Edit: January 2020
################################################################

library(ggplot2)
library(reshape2)
library(dplyr)
library(tidyr)
library(readr)

library("viridis") 
library(RColorBrewer)

source('../R/Log_file_analysis_functions.R')
source('../R/tree_comparison_functions.R')

theme_set(theme_light(base_size = 24, base_family = 'sans'))

################################################################
input_folder='../../data'
base_dir = input_folder

methods = c('Illumina_SPAdes', 'NP_Canu', 'NP_Canu_Hybrid_Polished', 'NP_SPAdes', 'NP_Unicycler', 
            'PB_Canu', 'PB_Canu_Hybrid_Polished', 'PB_SPAdes', 'PB_Unicycler')
method_labels = c('Illumina-SPAdes', 'NP-Canu', 'NP-Canu-Hybrid', 'NP-SPAdes-Hybrid', 'NP-Unicycler-Hybrid', 
                  'PB-Canu', 'PB-Canu-Hybrid', 'PB-SPAdes-Hybrid', 'PB-Unicycler-Hybrid')
names(method_labels) <- methods

################################################################
## Compare Plasmid clade probabilities - New version! ----

#generated by concat_plasmid_clade_probs_2() on individual clade probability files
clade_df <- read.csv(paste0(input_folder, '/plasmid_clade_comparison.csv'), stringsAsFactors = FALSE)

clade_df_y <- clade_df %>%
  select(Clade, clade_prob_y, method_y, alignment_method, plasmid)
colnames(clade_df_y) <- c("Clade", "clade_prob", "method", "alignment_method", "plasmid")

clade_df_x <- clade_df %>%
  select(Clade, clade_prob_x, method_x, alignment_method, plasmid)
colnames(clade_df_x) <- c("Clade", "clade_prob", "method", "alignment_method", "plasmid")

joint_clade_df <- rbind(clade_df_y, clade_df_x)
joint_clade_df <- unique(joint_clade_df)

for (alignment in c("roary")){
  for (plasmid in unique(joint_clade_df$plasmid)){
    clade_heatmap_by_plasmid(joint_clade_df, plasmid, alignment, method_labels)
    for (output_folder in c('../../figures/')){
      ggsave(paste0(output_folder,'/', plasmid,'_', alignment, '_heatmap.pdf'), plot=last_plot(), 
             width = 15, height = 20,
             device="pdf")
    }
  }
}

################################################################
## Compare cgMLST clade probabilities - New version! ----

#generated by concat_clade_probs() on individual clade probability files
clade_df <- read_csv('../../data/chrom_clade_comparison.csv')

clade_df_y <- clade_df %>%
  select(Clade, clade_prob_y, method_y)
colnames(clade_df_y) <- c("Clade", "clade_prob", "method")

clade_df_x <- clade_df %>%
  select(Clade, clade_prob_x, method_x)
colnames(clade_df_x) <- c("Clade", "clade_prob", "method")

joint_clade_df <- rbind(clade_df_y, clade_df_x)
joint_clade_df <- unique(joint_clade_df)

(clade_map <- clade_heatmap(joint_clade_df, method_labels))
ggsave("../../figures/cgmlst_heatmap.pdf",
       plot=clade_map, device="pdf")

################################################################
# cgmlst - tree heights ----

cgmlst_log_files <- sapply(methods, function(method) {paste0(input_folder, '/', method, 
                                                             '/cgmlst/fullgene_cgmlst/dated_tree/esbl_concat.log')})

tree_heights <- matrix(data=NA, nrow = length(cgmlst_log_files), ncol=3)

for (i in 1:length(cgmlst_log_files)){
  df <- prep_log_file(cgmlst_log_files[i])
  hpd_matrix <- HPD_from_df(df)
  tree_heights[i,] <- c(mean(df$TreeHeight.t), hpd_matrix[,'TreeHeight.t'])
}

colnames(tree_heights) <- c('Mean', 'HPD_low', 'HPD_up')
tree_heights <- data.frame(tree_heights)
tree_heights['method'] <- methods

tree_height_plot <- ggplot(tree_heights, aes(y=HPD_up, x=method)) +
  geom_errorbar(aes(ymin=HPD_low, ymax=HPD_up), width=0.2, size=1.2) +
  geom_point(aes(y=Mean), colour = "red", size=3) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5), 
        axis.title=element_text(size=24, face="bold")) +
  xlab("Assembly method") + ylab('Tree Height') + 
  scale_x_discrete(labels= method_labels)
tree_height_plot

ggsave(paste0("../../figures/cgmlst_tree_heights", clock, ".pdf"), 
       plot=last_plot(), device="pdf")

##########################
library(cowplot)
#clock = ""

clade_legend <- get_legend(clade_map)

all_plots <- plot_grid( clade_map + theme(legend.position = "none",
                                          axis.text.x = element_blank(), 
                                          axis.ticks.x = element_blank(),
                                          axis.title.x = element_blank()),
                        tree_height_plot,
                        align = "v",
                        nrow = 2, ncol = 1,
                        labels=c("A", "B"),
                        rel_heights = c(1, 1),
                        label_size = 15)

final_plot <- plot_grid(all_plots, clade_legend, ncol = 2, rel_widths = c(1, .2), align = "h", axis = "t")

ggsave("../../figures/cgmlst_tree_comp.pdf", 
       width = 15, height = 17, 
       plot=final_plot, device="pdf")

################################################################
# plasmid - tree heights ----

included_plasmids <- as_tibble(list(name = c('ColRNAI', "IncI1", "IncFIA", "IncFIB_AP001918")))

cgMLST_height_df <- read_csv(file = paste0(base_dir, '/cgMLST_height.csv')) %>%
  filter(plasmid %in% included_plasmids$name)

colour_map <- function(x){
  if (x == 'Illumina_SPAdes'){
    return(factor("Illumina_SPAdes", levels = c("Illumina_SPAdes", "NP_Canu", "Other")))
  } else if (x == "NP_Canu"){
    return(factor("NP_Canu", levels = c("Illumina_SPAdes", "NP_Canu", "Other")))
  } else {
    return(factor("Other", levels = c("Illumina_SPAdes", "NP_Canu", "Other")))
  }
}

for (fixed in c("")){
  
  all_tree_heights <- data.frame()
  
  for (method in methods){
    for (alignment_method in c('mauve', 'roary')){
      log_folder <- paste0(input_folder, '/plasmids/', alignment_method, '_results')
      all_log_files <- c(list.files(path=log_folder, pattern = paste0("*_subset", fixed,".log$"), recursive=FALSE, full.names = TRUE))
      method_log_files <- all_log_files[grep(method, basename(all_log_files))]
      
      other_method <- setdiff(grep(method, methods, value = TRUE), method)
      if (length(other_method)>0){
        method_log_files <- setdiff(method_log_files, grep(other_method, method_log_files, value = TRUE))
      }
      log_files <- setdiff(method_log_files, grep("_mauve.log", method_log_files, value = TRUE))
      
      tree_heights <- matrix(data=NA, nrow = length(log_files), ncol=3)
      for (i in 1:length(log_files)){
        df <- prep_log_file(log_files[i])
        hpd_matrix <- HPD_from_df(df)
        if('TreeHeight.t' %in% colnames(df)){
          tree_heights[i,] <- c(mean(df[, 'TreeHeight.t']), hpd_matrix[,'TreeHeight.t'])
        }
      }
      colnames(tree_heights) <- c('Mean', 'HPD_low', 'HPD_up')
      tree_heights <- data.frame(tree_heights)
      tree_heights['assembly_method'] <- method
      tree_heights['alignment_method'] <- alignment_method
      
      # extract plasmid names
      remove_parts <- paste(c(paste0(methods, "_"), c("_mauve.log", "_roary.log", ".log", "_subset", "_fixed")), collapse = "|")
      tree_heights['plasmid'] <- gsub(remove_parts, "", basename(log_files))
      
      all_tree_heights <- rbind(all_tree_heights, tree_heights)
    }
  }
  
  all_tree_heights['method'] <- paste0(all_tree_heights$assembly_method, '_',  all_tree_heights$alignment_method)
  
  subset_plasmid_tree_heights <- all_tree_heights[all_tree_heights$plasmid %in% included_plasmids$name,] %>%
    filter(alignment_method == 'roary') 
  
  for (depiction in c('', "_50","_100", "_log")){
    
    plasmid_height_plot <- ggplot(subset_plasmid_tree_heights, aes(y=HPD_up, x=assembly_method)) +
      geom_errorbar(aes(ymin=HPD_low, ymax=HPD_up, colour = sapply(assembly_method, colour_map)), 
                    width=0.2, size=1.2) +
      geom_point(aes(y=Mean, colour = sapply(assembly_method, colour_map)), size=3) +
      geom_boxplot(data = cgMLST_height_df, aes(y = cgMLST_height_df$height, x = assembly_method), 
                   alpha = .3) +
      labs(y = 'Tree Height',
           x = "Assembly method", color = "Assembly Method") +
      facet_wrap(vars(plasmid), nrow = 2, ncol = 2) + 
      scale_x_discrete(labels= method_labels) +
      scale_color_manual(values = c('red', 'black', 'grey')) +
      theme_minimal() + 
      theme(strip.text = element_text(size=20), 
            axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size=20), 
            axis.title=element_text(size=24, face="bold"),
            legend.position = 'bottom', 
            legend.title=element_text(size=24, face="bold") ) 
    
    if (depiction == '_log'){
      plasmid_height_plot <- plasmid_height_plot + 
        scale_y_continuous(trans = 'log', breaks = .base_breaks())
    } else if (depiction == '_50'){
      plasmid_height_plot <- plasmid_height_plot + 
        ylim(c(0, 50))
    } else if (depiction == '_100'){
      plasmid_height_plot <- plasmid_height_plot + 
        ylim(c(0, 100))
    }
    
    ggsave(paste0("../../figures/plasmid_tree_heights",fixed, depiction, ".pdf"), 
           width = 20, height = 15,
           plot=plasmid_height_plot, device="pdf")
    
  }
}
  